os: linux

dist: bionic

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.2
#  - 7.4

services:
  - mysql

env:
  - WP_VERSION=latest WP_MULTISITE=0
#  - WP_VERSION=5.6 WP_MULTISITE=0

jobs:
  include:
 #   - php: 7.2
 #     env: WP_VERSION=latest WP_MULTISITE=1 WPSNIFF=1
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=1 WPSNIFF=1

# export SNIFFS_DIR=$PWD/vendor/wp-coding-standards/wpcs,$PWD/vendor/phpcompatibility,$PWD/vendor/phpcompatibilityparagonie,; fi
# phpcs --config-set installed_paths $SNIFFS_DIR
before_script:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
      composer global require phpunit/phpunit ^5 yoast/phpunit-polyfills
    else
      composer global require phpunit/phpunit ^7 yoast/phpunit-polyfills
    fi
  - |
  - |
    if [[ "$WPSNIFF" == "1" ]]; then
      composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
      composer global require wp-coding-standards/wpcs phpcompatibility/phpcompatibility-wp
      composer global require dealerdirect/phpcodesniffer-composer-installer
      phpcs -i
    fi
  - |

script:
  - if [[ "$WPSNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml --extensions=php .; fi
  - phpunit
